# Generated by Django 3.2 on 2023-03-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='user',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='phone',
            field=models.IntegerField(blank=True),
        ),
    ]
